@startgantt

ganttscale weekly

Project starts 2021-08-01

-- cronograma -- 
[completado] is colored in green
[completado] starts 2021-08-03 and ends 2021-09-29
[falta] starts 2021-09-29 and ends 2021-12-07
[falta] is colored in blue

-- Aulas -- 
[Termo] is colored in Red
[Termo]  starts 2021-08-03 and ends 2021-08-17
[Aula01] starts 2021-08-03 and ends 2021-08-03
[Aula02] starts 2021-08-10 and ends 2021-08-10
[Aula03] starts 2021-08-17 and ends 2021-08-17
note bottom
Entrega: Termo de Compromisso
end note
[Pré-projeto (BCC)] starts at [Termo]'s end
[Pré-projeto (BCC)] ends 2021-09-28
[Pré-projeto (SIS)] starts at [Termo]'s end
[Pré-projeto (SIS)] ends 2021-10-05
[Aula04] starts 2021-08-24 and ends 2021-08-24
[Aula05] starts 2021-08-31 and ends 2021-08-31
[Aula06] starts 2021-09-07 and ends 2021-09-07
[Aula07] starts 2021-09-14 and ends 2021-09-14
[Aula08] starts 2021-09-21 and ends 2021-09-21
[Aula09] starts 2021-09-28 and ends 2021-09-28
note bottom
Entrega: Pré-projeto (BCC) 
end note
[Aula10] starts 2021-10-05 and ends 2021-10-05
note bottom
Entrega: Pré-projeto (SIS) 
end note
[Projeto] starts at [Pré-projeto (BCC)]'s end with green dashed link
[Projeto] ends 2021-11-30
[Aula11] starts 2021-10-12 and ends 2021-10-12
[Aula12] starts 2021-10-19 and ends 2021-10-19
note bottom
Bancas (BCC) 
end note
[Aula13] starts 2021-10-26 and ends 2021-10-26
[Aula14] starts 2021-11-02 and ends 2021-11-02
[Aula15] starts 2021-11-09 and ends 2021-11-09
[Aula16] starts 2021-11-16 and ends 2021-11-16
[Aula17] starts 2021-11-23 and ends 2021-11-23
[Aula18] starts 2021-11-30 and ends 2021-11-30
note bottom
Entrega: Projeto 
end note
[Final] starts at [Projeto]'s end with blue dashed link
[Final] ends 2021-12-07
[Aula19] starts 2021-12-07 and ends 2021-12-07

-- Feriados --
[Independência] starts 2021-09-07 and ends 2021-09-07
[Aparecida] starts 2021-10-12 and ends 2021-10-12


@endgantt