@startgantt

ganttscale weekly

Project starts 2022-02-23

-- cronograma -- 
[completado] is colored in green
[completado] starts 2022-02-23 and ends 2022-03-16
[falta] starts 2022-03-16 and ends 2022-06-22
[falta] is colored in blue

-- Aulas -- 
[Termo] is colored in Red
[Termo]  starts 2022-02-23 and ends 2022-03-09
[Aula01] starts 2022-02-23 and ends 2022-02-23
[Aula02] starts 2022-03-02 and ends 2022-03-02
[Aula03] starts 2022-03-09 and ends 2022-03-09
note bottom
Entrega: Termo de Compromisso
end note
[Pré-projeto (BCC)] starts at [Termo]'s end
[Pré-projeto (BCC)] ends 2022-04-20
[Pré-projeto (SIS)] starts at [Termo]'s end
[Pré-projeto (SIS)] ends 2022-04-27
[Aula04] starts 2022-03-16 and ends 2022-03-16
[Aula05] starts 2022-03-23 and ends 2022-03-23
[Aula06] starts 2022-03-30 and ends 2022-03-30
[Aula07] starts 2022-04-06 and ends 2022-04-06
[Aula08] starts 2022-04-13 and ends 2022-04-13
[Aula09] starts 2022-04-20 and ends 2022-04-20
note bottom
Entrega: Pré-projeto (BCC) 
end note
[Aula10] starts 2022-04-27 and ends 2022-04-27
note bottom
Entrega: Pré-projeto (SIS) 
end note
[Projeto] starts at [Pré-projeto (BCC)]'s end with green dashed link
[Projeto] ends 2022-06-08
[Aula11] starts 2022-05-04 and ends 2022-05-04
note bottom
Bancas (BCC) 
end note
[Aula12] starts 2022-05-11 and ends 2022-05-11
[Aula13] starts 2022-05-18 and ends 2022-05-18
[Aula14] starts 2022-05-25 and ends 2022-05-25
[Aula15] starts 2022-06-01 and ends 2022-06-01
[Aula16] starts 2022-06-08 and ends 2022-06-08
note bottom
Entrega: Projeto 
end note
[Final] starts at [Projeto]'s end with blue dashed link
[Final] ends 2022-06-08
note bottom
Avaliações: Projetos
end note
[Aula17] starts 2022-06-15 and ends 2022-06-15
[Aula18] starts 2022-06-22 and ends 2022-06-22

@endgantt